package View;

import Aksesdata.AksesDataGlobal;
import Aksesdata.AksesDataTransaksiJual;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class MenuTransaksiJual extends javax.swing.JFrame {

    AksesDataTransaksiJual aksesDataTransaksiJual;

    /**
     * Creates new form Transaksijual_07046
     */
    public MenuTransaksiJual() throws SQLException {
        initComponents();
        this.aksesDataTransaksiJual = new AksesDataTransaksiJual();
        this.setTitle("Menu Transaksi Jual");
        this.setLocationRelativeTo(null);
        this.setTextKodeJual();
        this.setTextKodeAdmin();
        this.setTabelModel();
        this.setVisible(true);
    }

    public void setTextKodeJual() throws SQLException {
        this.tfKodeJual.setEditable(false);
        this.tfKodeJual.setEnabled(false);
        int kodeJual = this.aksesDataTransaksiJual.getSequenceKodeTransaksiJual();
        this.tfKodeJual.setText(String.valueOf(kodeJual));
    }

    public void setTextKodeAdmin() throws SQLException {
        this.tfKodeAdmin.setEditable(false);
        this.tfKodeAdmin.setEnabled(false);
        this.tfKodeAdmin.setText(String.valueOf(AksesDataGlobal.kodeAdmin));
    }

    public void setTabelModel() throws SQLException {
        this.tblTransaksiJual.setModel(this.aksesDataTransaksiJual.viewTabel());
    }

    private boolean cekSemuaTextKosong() {
        boolean textKosong = false;
        if (this.tfKodeJual.getText().isEmpty()
                || this.tfKodeAdmin.getText().isEmpty()
                || this.tfKodePembeli.getText().isEmpty()
                || this.tfKodeMotor.getText().isEmpty()
                || this.tfTanggalBeli.getText().isEmpty()) {
            textKosong = true;
        }
        return textKosong;
    }

    public void refreshField() {
        this.tfKodePembeli.setText("");
        this.tfKodeMotor.setText("");
        this.tfTanggalBeli.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfKodeJual = new javax.swing.JTextField();
        tfKodeAdmin = new javax.swing.JTextField();
        tfKodePembeli = new javax.swing.JTextField();
        tfKodeMotor = new javax.swing.JTextField();
        tfTanggalBeli = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksiJual = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kode_jual");

        jLabel2.setText("Kode_admin");

        jLabel3.setText("Kode_pembeli");

        jLabel4.setText("Kode_motor");

        jLabel5.setText("Tanggal_beli");

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblTransaksiJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "kode_jual", "kode_admin", "kode_pembeli", "kode_motor", "tanggal_beli"
            }
        ));
        jScrollPane1.setViewportView(tblTransaksiJual);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfKodeAdmin)
                            .addComponent(tfKodePembeli)
                            .addComponent(tfKodeMotor)
                            .addComponent(tfTanggalBeli)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfKodeJual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInsert)
                        .addGap(40, 40, 40)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfKodeJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfKodeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfKodePembeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfKodeMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfTanggalBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInsert)
                            .addComponent(btnBack))))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new MenuLogin();
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        if (cekSemuaTextKosong()) {
            JOptionPane.showMessageDialog(null, "Isi semua kolom isian terlebih dahulu",
                    "Gagal Insert", WARNING_MESSAGE);
        } else {
            try {
                int konfirmasi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk input data "
                        + "transaksi jual ?", "Konfirmasi", OK_CANCEL_OPTION, QUESTION_MESSAGE);
                if (konfirmasi == 0) {
                    int kodeJual = Integer.parseInt(tfKodeJual.getText());
                    int kodeAdmin = AksesDataGlobal.kodeAdmin;
                    int kodePembeli = Integer.parseInt(tfKodePembeli.getText());
                    int kodeMotor = Integer.parseInt(tfKodeMotor.getText());
                    String tanggalBeli = this.tfTanggalBeli.getText();
                    this.aksesDataTransaksiJual.insert(kodeJual, kodeAdmin, kodePembeli, kodeMotor, tanggalBeli);
                }
                this.setTabelModel();
                JOptionPane.showMessageDialog(null, "Input data transaksi jual berhasil");
                this.setTextKodeJual();
                this.refreshField();
            } catch (SQLException ex) {
                Logger.getLogger(MenuTransaksiJual.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnInsertActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksiJual;
    private javax.swing.JTextField tfKodeAdmin;
    private javax.swing.JTextField tfKodeJual;
    private javax.swing.JTextField tfKodeMotor;
    private javax.swing.JTextField tfKodePembeli;
    private javax.swing.JTextField tfTanggalBeli;
    // End of variables declaration//GEN-END:variables
}
